steps:
  # Build Docker Image & Pass the Key
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}',
      '-t',
      'gcr.io/$PROJECT_ID/style-confident-ai:$COMMIT_SHA',
      '.'
    ]

  # Push Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/style-confident-ai:$COMMIT_SHA']

  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'digitalstylist'
      - '--image'
      - 'gcr.io/$PROJECT_ID/style-confident-ai:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _VITE_GEMINI_API_KEY: 'PLACEHOLDER'

images:
  - 'gcr.io/$PROJECT_ID/style-confident-ai:$COMMIT_SHA'
