# We only need Nginx now, because the build happens in Cloud Build
FROM nginx:alpine

# Copy the 'dist' folder generated by the previous step
COPY dist /usr/share/nginx/html

# Copy Config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
