server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # React Router Handler
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache Images (Important for your Wardrobe/Result images)
    location ~* \.(jpg|jpeg|png|gif|ico)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}
